### ISSUE TITLE
crash with default color

### ISSUE THREAD

**Issue by ThomasWaldmann** [bwghughes/gerbil#7]
There's an issue with the default font color value:
```
$ gerbil -i in.pdf -o out.pdf -t "Foo Bar" -f /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
Traceback (most recent call last):
  File "/home/tw/w/watermark-env/bin/gerbil", line 9, in <module>
    load_entry_point('gerbil==1.5.5', 'console_scripts', 'gerbil')()
  File "/home/tw/w/watermark-env/local/lib/python2.7/site-packages/gerbil/__init__.py", line 65, in main
    f, err = create_footer(options)
  File "/home/tw/w/watermark-env/local/lib/python2.7/site-packages/gerbil/gerbil.py", line 76, in create_footer
    color = colors.HexColor(options.font_color)
  File "/home/tw/w/watermark-env/local/lib/python2.7/site-packages/reportlab/lib/colors.py", line 385, in HexColor
    return Color(((val>>16)&0xFF)/255.0,((val>>8)&0xFF)/255.0,(val&0xFF)/255.0)
TypeError: unsupported operand type(s) for >>: 'instance' and 'int'
```

**Comment by ThomasWaldmann** [comment]
https://github.com/bwghughes/gerbil/commit/145b3a73a5862547c5f6bc67671f642c24a63259

is that the fix,  just not on pypi yet?

**Comment by bwghughes** [comment]
Ok thanks for raising - I'll look into it this morning.

**Comment by bwghughes** [comment]
Thomas - just pushed 1.5.6 onto Pypy silly bug. Which would have been caught with proper tests - so once I've finished lashing myself with birch, I'll spend some time today bringing the testing up to scratch. Have tested on 2.7.9 using the command you used (albeit on OS X).

**Comment by ThomasWaldmann** [comment]
Thanks! It's fixed in 1.5.6, I just tried it.

**Comment by bwghughes** [comment]
@ThomasWaldmann glad fine - just finishing off tests. If you're keen, we're just about to launch a cloud based gerbil, backed by S3 with rest api and bulk stamping - we'd be happy to open it up to you for use if it would fit your use case. Let me know.

**Comment by ThomasWaldmann** [comment]
@bwghughes thanks for the offer, but my use case relates to copyrighted material, so I must not upload that to a cloud based service.
